### ISSUE TITLE
Servo Problems

### ISSUE THREAD

**Issue by tingles2233** [DWiskow/grbl1-1g-Servo#1]
Not sure if this is still monitored, hopefully it is. 

I tried to apply the spindle update code as directed, however I am having some weird symptoms. 

Background: 
Custom CoreXY build. 
X / Y movements working as expected
Testing with this servo,     https://www.amazon.ca/gp/product/B01NA80LUR/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1

Problem/Result:
After flashing the board and sending M3/M5 commands the servo holds a position, occasionally twitches (Small mm movements), but does not move more then these twitches. 

Any suggestions? I have played with quite a few different servo Pulse settings but no change in results. Tested the signal pin in both the spin dir and Spin Enable

Hopefully something simple I am missing, but starting to get lost in where to check

**Comment by tingles2233** [comment]
Just talked to a buddy and he reminded me that the Z-Limit and Spin En switch on Uno boards with 1.1. I will test tonight and update. Might be my problem.

**Comment by tingles2233** [comment]
Confirmed still an issue and not working.

**Comment by UR-369** [comment]
I HAVE THE SAME ISSUE HAVE U FIX IT ??

**Comment by kondziogithub** [comment]
I have the same problem and cannot track down what's causing the twitches.  I nailed the symptoms though:
The movement of both axis by itself is good. Homing is working as expected (CoreXY). When the servo is engaged (after M3) and the machine movement is initiated the servo is holding steady as expected.  When the servo is off (after M5) and the machine is in process of movement (X or Y axis) the servo twitches constantly until the axis movement stops.
I just tested it with the Grbl 1.1f and Grbl 1.1h (latest I think).  I could not find 1.1g.

I really would like to find this bug.  If anyone with more experience in this source would be willing to dig, I'd greatly appreciate it.  Thanks!

**Comment by danielgimeno** [comment]
Same issue here. connecting servo mg90s, while traveling has a random movement. Sending m3 and M5 has no effect. 
Perhaps the frequencies in spindle-control.c are wrong? I have never needed to modify these frequencies. 
I'm using 1.1h perhaps going back to 1.1g solve the problem
Thank you for your time

**Comment by beamzer** [comment]
I used https://github.com/lavolpecheprogramma/grbl-1-1h-servo with the smaller sg90, and that works perfect. The MG90s works on the same frequency (50Hz) so it should also work. Remember to use a separate powersupply for the MG90s, it requires more current than what a typical microcontroller can supply.

**Comment by murilobaliego** [comment]
Hi all, anyone solved that issue, I got the same issue. On 0.9i this issue does not happen on servo, but CoreXY homing does not work there. So I really would like to use this newer version.

**Comment by beamzer** [comment]
did you try https://github.com/lavolpecheprogramma/grbl-1-1h-servo ?

**Comment by murilobaliego** [comment]
Yes, I got the same problem. I checked the code and in my opinion the problem is on function spindle_stop()
More exactly on this line inside this function:
SPINDLE_TCCRA_REGISTER |= (1<<SPINDLE_COMB_BIT); // Ensure PWM output is enabled.                   // RC Servo

It is not a solution, but I commented this line above inside spindle_stop() and it fixed the issue but the M5 stopped to work, if anyone has any suggestion I can try.

**Comment by murilobaliego** [comment]
One workaround that I found is to use the Inkscape extension called [J-Tech-Photonics-Laser-Tool](https://github.com/JTechPhotonics/J-Tech-Photonics-Laser-Tool) to generate the GCode for the servo where you can customize the commands to up and down the pen. Then I used M3 S140 for Pen down and M3 S1 for Pen up (instead of M5). In this way the servo is constantly engaged and during drawing this issue with servo twitches is eliminated.
But when homing the machine or using jog commands the servo twitches persists of course.

**Comment by zanganeh** [comment]
I have the same issue. What I've done and seems working for me is to change spindle_stop to:

void spindle_stop()
{
      #ifdef RC_SERVO_INVERT 
          SPINDLE_OCR_REGISTER = RC_SERVO_LONG;
      #else
          SPINDLE_OCR_REGISTER = RC_SERVO_SHORT;
      #endif  
}

Not sure if it is 100% right or not! I've got the idea from Grbl 0.9 servo samples. I hope it helps.
